#pragma once

#include <array>
#include <cstdint>

enum class AddressingMode
{
  NONE,
  IMP,
  R_D16,
  R_R,
  MR_R,
  R,
  R_D8,
  R_MR,
  R_HLI,
  R_HLD,
  HLI_R,
  HLD_R,
  R_A8,
  A8_R,
  HL_SPR,
  D16,
  D8,
  D16_R,
  MR_D8,
  MR,
  A16_R,
  R_A16
};

enum class InstructionType
{
  NONE,
  NOP,
  LD,
  INC,
  DEC,
  RLCA,
  ADD,
  RRCA,
  STOP,
  RLA,
  JR,
  RRA,
  DAA,
  CPL,
  SCF,
  CCF,
  HALT,
  ADC,
  SUB,
  SBC,
  AND,
  XOR,
  OR,
  CP,
  POP,
  JP,
  PUSH,
  RET,
  CB,
  CALL,
  RETI,
  LDH,
  JPHL,
  DI,
  EI,
  RST,
  ERR,
  RLC,
  RRC,
  RL,
  RR,
  SLA,
  SRA,
  SWAP,
  SRL,
  BIT,
  RES,
  SET
};

enum class RegisterType
{
  NONE,
  A,
  F,
  B,
  C,
  D,
  E,
  H,
  L,
  AF,
  BC,
  DE,
  HL,
  SP,
  PC
};

enum class ConditionType
{
  NONE,
  NZ,
  Z,
  NC,
  C
};

struct Instruction
{
  InstructionType instruction;
  AddressingMode addressMode;
  RegisterType reg1;
  RegisterType reg2;
  ConditionType condition;
  uint8_t parameter;
};

constexpr std::array<Instruction, 256> INSTRUCTIONS = {{
    {InstructionType::NOP, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D16, RegisterType::BC, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::BC, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::BC, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::B, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::B, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::B, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RLCA, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::A16_R, RegisterType::NONE, RegisterType::SP, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::HL, RegisterType::BC, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::A, RegisterType::BC, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::BC, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::C, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::C, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::C, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RRCA, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::STOP, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D16, RegisterType::DE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::DE, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::DE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::D, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::D, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::D, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RLA, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JR, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::HL, RegisterType::DE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::A, RegisterType::DE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::DE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::E, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::E, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::E, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RRA, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JR, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::NZ, 0},
    {InstructionType::LD, AddressingMode::R_D16, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::HLI_R, RegisterType::HL, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::H, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::H, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::H, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DAA, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JR, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::Z, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::HL, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_HLI, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::L, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::L, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::L, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CPL, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JR, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::NC, 0},
    {InstructionType::LD, AddressingMode::R_D16, RegisterType::SP, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::HLD_R, RegisterType::HL, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::SP, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::MR, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::MR, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_D8, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::SCF, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JR, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::C, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::HL, RegisterType::SP, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_HLD, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::SP, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::INC, AddressingMode::R, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::DEC, AddressingMode::R, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CCF, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::B, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::B, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::C, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::C, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::D, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::D, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::E, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::E, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::H, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::H, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::L, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::L, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::HALT, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::HL, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::B, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::D, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::E, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::H, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::L, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_MR, RegisterType::A, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_R, RegisterType::A, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::RET, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NZ, 0},
    {InstructionType::POP, AddressingMode::R, RegisterType::BC, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JP, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NZ, 0},
    {InstructionType::JP, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CALL, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NZ, 0},
    {InstructionType::PUSH, AddressingMode::R, RegisterType::BC, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::ADD, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x0},
    {InstructionType::RET, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::Z, 0},
    {InstructionType::RET, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JP, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::Z, 0},
    {InstructionType::CB, AddressingMode::D8, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CALL, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::Z, 0},
    {InstructionType::CALL, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::ADC, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x8},
    {InstructionType::RET, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NC, 0},
    {InstructionType::POP, AddressingMode::R, RegisterType::DE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JP, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NC, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CALL, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::NC, 0},
    {InstructionType::PUSH, AddressingMode::R, RegisterType::DE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::SUB, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x10},
    {InstructionType::RET, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::C, 0},
    {InstructionType::RETI, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JP, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::C, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CALL, AddressingMode::D16, RegisterType::NONE, RegisterType::NONE, ConditionType::C, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::SBC, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x18},
    {InstructionType::LDH, AddressingMode::A8_R, RegisterType::NONE, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::POP, AddressingMode::R, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::MR_R, RegisterType::C, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::PUSH, AddressingMode::R, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::AND, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x20},
    {InstructionType::ADD, AddressingMode::R_D8, RegisterType::SP, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::JP, AddressingMode::R, RegisterType::HL, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::A16_R, RegisterType::NONE, RegisterType::A, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::XOR, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x28},
    {InstructionType::LDH, AddressingMode::R_A8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::POP, AddressingMode::R, RegisterType::AF, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_MR, RegisterType::A, RegisterType::C, ConditionType::NONE, 0},
    {InstructionType::DI, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::PUSH, AddressingMode::R, RegisterType::AF, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::OR, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x30},
    {InstructionType::LD, AddressingMode::HL_SPR, RegisterType::HL, RegisterType::SP, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_R, RegisterType::SP, RegisterType::HL, ConditionType::NONE, 0},
    {InstructionType::LD, AddressingMode::R_A16, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::EI, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::NONE, AddressingMode::NONE, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::CP, AddressingMode::R_D8, RegisterType::A, RegisterType::NONE, ConditionType::NONE, 0},
    {InstructionType::RST, AddressingMode::IMP, RegisterType::NONE, RegisterType::NONE, ConditionType::NONE, 0x38}
}};
